# Generated by Django 4.2 on 2025-04-08 12:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_consulta_data_alter_medico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 8, 12, 43, 0, 971419, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('ORTOPEDIA', 'Ortopedia'), ('DERMATOLOGIA', 'Dermatologia'), ('CARDIOLOGIA', 'CAR'), ('OFTALMOLOGIA', 'Oftalmologia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
