# Generated by Django 4.2 on 2025-04-08 13:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_consulta_data_alter_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 8, 13, 5, 14, 813777, tzinfo=datetime.timezone.utc))]),
        ),
    ]
