# Generated by Django 4.2 on 2025-04-08 13:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_consulta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 8, 13, 49, 12, 889805, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('ORTOPEDIA', 'Ortopedia'), ('DERMATOLOGIA', 'Dermatologia'), ('CAR', 'CAR'), ('OFTALMOLOGIA', 'Oftalmologia')], max_length=20),
        ),
    ]
